services:
  - type: web
    name: deathrow-scraper
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn death:app --bind 0.0.0.0:$PORT
    autoDeploy: true
